name: Auto Assign Newly Opened Issues To Symbiota Triage Project
on:
  issues:
    types: 
      - opened
      - reopened
  pull_request:
    types: 
      - opened
      - reopened
      - review_requested
      
env:
  todo: Organize

jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v1.2.0
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          organization: BioKIC
          project_id: 2
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status
    
